### ISSUE TITLE
Touch Gesture Support

### ISSUE THREAD

**Issue by Purus** [fiestah/angular-gallery-directive#3]
It would be great, if it supports touch gestures for swiping left and right. Navigation in mobile will be good with this.

**Comment by thatmarvin** [comment]
This should work out of the box with [ngTouch](https://docs.angularjs.org/api/ngTouch):

``` html
<div gallery-item-list ng-swipe-left="nextScreen()" ng-swipe-right="previousScreen()">
   …
</div>
```

Another way is by ignoring the directive's per-item/screen nav altogether and use native momentum scroll. Roughly, you need the following CSS overrides:

``` css
[gallery] {
  overflow-x: scroll;
  -webkit-overflow-scrolling: touch;
}

[gallery-window] {
  overflow: visible;
}
[gallery-item-list] {
  position: static;
}

```

See example on www.fiestah.com under "Find it all on Fiestah" (make sure your browser window is narrow enough)
